version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: alurafake-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: alurafake_db
      MYSQL_USER: alura_user
      MYSQL_PASSWORD: alura_pass
      TZ: "America/Sao_Paulo"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: