ALTER TABLE TaskAnswer DROP FOREIGN KEY FK_TaskAnswer_Task;

ALTER TABLE Task MODIFY id INT(20) NOT NULL;
ALTER TABLE TaskAnswer MODIFY id INT(20) NOT NULL;
ALTER TABLE TaskAnswer MODIFY task_id INT(20) NOT NULL;

ALTER TABLE TaskAnswer
    ADD CONSTRAINT FK_TaskAnswer_Task
        FOREIGN KEY (task_id) REFERENCES Task(id) ON DELETE CASCADE;