ALTER TABLE TaskAnswer DROP FOREIGN KEY FK_TaskAnswer_Task;

ALTER TABLE Task MODIFY id BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE TaskAnswer MODIFY id BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE TaskAnswer MODIFY task_id BIGINT(20) NOT NULL;

ALTER TABLE TaskAnswer
    ADD CONSTRAINT FK_TaskAnswer_Task
        FOREIGN KEY (task_id) REFERENCES Task(id) ON DELETE CASCADE;
